### ISSUE TITLE
想问下为什么点击阅读模式但是弹出空白页面啊

### ISSUE THREAD

**Issue by oliveryen** [guopenghui/obsidian-language-learner#102]
<img width="730" alt="image" src="https://user-images.githubusercontent.com/31887766/218410286-9ee96fc4-53b0-4e8c-9d34-009f53d7ebba.png">

**Comment by guopenghui** [comment]
空白是解析过程中出错了，按`Ctrl + Shift + i`打开控制台，然后复现一下，看有没有报错信息

**Comment by oliveryen** [comment]
已经解决了，谢谢 是我的article前面多了空格
