### ISSUE TITLE
您好，我怎么没有阅读模式啊？

### ISSUE THREAD

**Issue by keen0309** [guopenghui/obsidian-language-learner#12]
您好，我怎么没有阅读模式啊？
![image](https://user-images.githubusercontent.com/103982843/174620524-3a7842d0-b6fe-4de1-9cef-ab7cb7a9ece7.png)

**Comment by keen0309** [comment]
![image](https://user-images.githubusercontent.com/103982843/174621655-40d1cb1f-3741-4b36-8dc2-4630ff2c769e.png)

**Comment by guopenghui** [comment]
`langr-audio: `后面不要换行，链接应该和这个在一行

**Comment by keen0309** [comment]
> `langr-audio: `后面不要换行，链接应该和这个在一行

![image](https://user-images.githubusercontent.com/103982843/174623975-50feb468-b829-45b4-81c5-260e8959e632.png)
好像还是没阅读模式

**Comment by keen0309** [comment]
![image](https://user-images.githubusercontent.com/103982843/174624148-fb8fc714-af2a-46be-bd6b-443280a887af.png)

**Comment by keen0309** [comment]
能否发个样图我看下

**Comment by keen0309** [comment]
![image](https://user-images.githubusercontent.com/103982843/174625123-37ce6fa3-ea59-45a8-be6e-06fa4fbcc5d3.png)

**Comment by guopenghui** [comment]
你看行号，你的`langr-audio`是在第3行，但是下面的链接却在第4行。 应该是因为这个发生了解析错误。 把第3行和第4行的链接合并起来。（注意冒号后面要有一个空格）

![image](https://user-images.githubusercontent.com/13451866/174628501-4bd2353d-db41-4b4d-b7b3-cc4295912ad4.png)

**Comment by keen0309** [comment]
![image](https://user-images.githubusercontent.com/103982843/174631519-4c2d0b28-9158-4eb0-8005-a0fdb1574033.png)
还是没有阅读模式

**Comment by keen0309** [comment]
![image](https://user-images.githubusercontent.com/103982843/174631870-f67587b2-9622-4a04-830f-fff290cb2a5e.png)
you'l有了 但是我怎么加音频呢？这篇文章

**Comment by guopenghui** [comment]
你看一下使用指南吧，按照【解析页面】部分的格式来写：
https://github.com/guopenghui/obsidian-language-learner/blob/master/public/tutorial.pdf

**Comment by keen0309** [comment]
> 你看一下使用指南吧，按照【解析页面】部分的格式来写： https://github.com/guopenghui/obsidian-language-learner/blob/master/public/tutorial.pdf 正是看了  才问的。我想请教下 怎么给我这篇文章加语音 我加了 就识别不到了 ba把蓝色的链接去掉就能了。但是没音频
![image](https://user-images.githubusercontent.com/103982843/174633377-9348a8a5-7ab6-4989-9dcf-3562aa73535e.png)

**Comment by keen0309** [comment]
![image](https://user-images.githubusercontent.com/103982843/174633548-02b8a501-3095-4422-b298-52ce67a87709.png)

**Comment by keen0309** [comment]
![image](https://user-images.githubusercontent.com/103982843/174633594-45e6e859-1827-4c84-8877-f9a980483942.png)
没有音频

**Comment by guopenghui** [comment]
再对比一下，文章是放在后面的，不是在frontmatter里面
![image](https://user-images.githubusercontent.com/13451866/174634403-11d5c962-93c0-406d-bbfa-038080820f77.png)

**Comment by keen0309** [comment]
我试了好几次文章放后边识别不了。放在frontmatter后边识别了。链接识别不了。好奇怪

**Comment by keen0309** [comment]
我少打了word. 夹在中间的部分。。那音频怎么加呢

**Comment by keen0309** [comment]
![image](https://user-images.githubusercontent.com/103982843/174637484-a7e2ff76-4edf-4ee2-a781-7356ca9cdfbe.png)

**Comment by keen0309** [comment]
没音频

**Comment by guopenghui** [comment]
> 没音频

我发的那篇有吗

**Comment by keen0309** [comment]
有的。你发的是可以的 ，我这个是不是得去wiki找 然后替换链接  但是没找到

**Comment by keen0309** [comment]
这个音频 有局限性 没法做到lingq 直接读吧 。还得找资源

**Comment by guopenghui** [comment]
![image](https://user-images.githubusercontent.com/13451866/174638440-e8e6f570-6a95-4602-ac65-fe26e1276523.png)

大小写
