### ISSUE TITLE
想问下为什么一直无法显示音频

### ISSUE THREAD

**Issue by candydate1234** [guopenghui/obsidian-language-learner#120]
![image](https://user-images.githubusercontent.com/130087113/230451470-154dadf4-e099-4b99-8eef-4b78540304a1.png)

**Comment by IceBerrggg** [comment]
> 可能这个链接最终没有直接指向一个音频文件

我按照您说的方法试过，在自己的仓库里不好用，但是放到下载的仓库里就好用，很奇怪

**Comment by guopenghui** [comment]
最新版本里面 url 的解析出了点问题，后面我修复后更新一下

**Comment by guopenghui** [comment]
0.2.7 中已修复
