### ISSUE TITLE
在哪里找自己文章的音频啊？

### ISSUE THREAD

**Issue by keen0309** [guopenghui/obsidian-language-learner#14]
![image](https://user-images.githubusercontent.com/103982843/174683900-8f90494a-5e8c-4eae-abd1-f9cdec8eba5e.png)
xiang想找这个私人谈话和自己文章的音频

**Comment by guopenghui** [comment]
直接在网上找，英文演讲比较好找，其他的不太清楚。我自己只有演讲稿用了这个音频功能。
