### ISSUE TITLE
[bug]按照Tutoial的格式，不能正确解析页面

### ISSUE THREAD

**Issue by chen-huaneng** [guopenghui/obsidian-language-learner#147]
我根据Tutorial的步骤操作正确地将插件放在了.obsidian文件夹下的plugins文件夹中，并且能够正确地加载和设置插件的功能，但是写好了页面的格式，在Obsidian的页面展示中不能正确地解析页面，为了方便展示，我没有用大段的文本来解析，但是使用大段文本解析的结果是一样的，同样不能够正确展示。  
插件的版本是0.2.5，Obsidian的版本是1.3.7  
以下分别是阅读模式和编辑模式：  
![QQ截图20230817091627](https://github.com/guopenghui/obsidian-language-learner/assets/113616701/9c90a9d8-ac58-427c-b450-2224b17c2629)
![QQ截图20230817091639](https://github.com/guopenghui/obsidian-language-learner/assets/113616701/ac1ded72-ed5a-4775-b235-fed799be6d14)
![QQ截图20230817091941](https://github.com/guopenghui/obsidian-language-learner/assets/113616701/73308995-3d04-43bb-afc4-3dc1e72ae139)
![QQ截图20230817092244](https://github.com/guopenghui/obsidian-language-learner/assets/113616701/b6219fbd-e3e3-4e6b-9822-2b6c814c61fa)

**Comment by guopenghui** [comment]
应该是没点对按钮，不是点那个进入markdown预览模式的按钮，而是另外一个进入阅读模式的按钮

**Comment by chen-huaneng** [comment]
> 应该是没点对按钮，不是点那个进入markdown预览模式的按钮，而是另外一个进入阅读模式的按钮

好的感谢作者，经过我的尝试已经解决了，一共是有三个模式，一个是编辑，一个预览，还有一个阅读模式。
![QQ截图20230817093053](https://github.com/guopenghui/obsidian-language-learner/assets/113616701/96fd225e-9e0b-4c19-806c-ad407e3d4f31)
