### ISSUE TITLE
希望可以对长难句的句子成分进行分析

### ISSUE THREAD

**Issue by Fang2223333** [guopenghui/obsidian-language-learner#160]
有些长难句阅读起来比较复杂，希望可以通过不同颜色的下划线来标注句子中不同的成分（主语插入语从句等等）

**Comment by guopenghui** [comment]
这个实现起来难度比较大，而且阅读本身就是要锻炼自己的句子分析能力，插件不好去代替自己去分析

**Comment by Fang2223333** [comment]
是我的表述问题，我想说的是可以增加添加下划线的功能，让使用者能更方便的分析句子成分😂

**Comment by athlan20** [comment]
我也希望在阅读模式的时候可以做一些标注，比如自己可以划一下主谓宾
