### ISSUE TITLE
创建新单词的时候，能否自动刷新 单词数据库 和 复习数据库？

### ISSUE THREAD

**Issue by pendel** [guopenghui/obsidian-language-learner#17]
或者是我没找到方法？
每次创建新单词之后，都要手动点击刷新。
因为我用的nextcloud同步，检测到文件有改动时就会自动上传到云，不需要像其它同步工具一样手动同步，所以经常会忘记刷新 单词数据库 和 复习数据库。

**Comment by guopenghui** [comment]
`0.1.0`版本中已更新

**Comment by DTIM001** [comment]
棒！
