### ISSUE TITLE
划词后词典无法给出翻译内容

### ISSUE THREAD

**Issue by kresely** [guopenghui/obsidian-language-learner#187]

**Comment by kresely** [comment]
制作人你好，非常感谢您的发明，对我的英语学习很有帮助
我今天碰到划词后词典无法给出翻译内容的问题，自己无法解决，想请教一下您
检查过网络问题，尝试重装软件皆无果，
![image](https://github.com/user-attachments/assets/93d995ac-76e8-482b-8d36-3c0f47d517d4)
请问我应该如何解决？

**Comment by guopenghui** [comment]
可能是网络原因？ 我试了一下，我这边能正常出来翻译

**Comment by kresely** [comment]
> 可能是网络原因？ 我试了一下，我这边能正常出来翻译

我个人试过周围几个网络和热点，电脑在下载文件和浏览器加载中都正常，我也尝试了一下旧版本的查询功能，
旧版本会给出如下报错
![image](https://github.com/user-attachments/assets/913b8018-8e4f-40c0-8a64-5f50cbafd58c)
本人对网络问题一窍不通，不太懂该如何修改
还有就是，我最近下载过pycharm、anacanda，会不会是调试过程的错误波及到这里

**Comment by kresely** [comment]
问题解决了！原因是hosts配置错误，后来人如果出现类似问题可以在blibli搜索“清水寺下定终身”，
感谢树哥指路，的确是网络问题！
