### ISSUE TITLE
请问下这个是已经放弃开发了吗

### ISSUE THREAD

**Issue by DreamAfar** [guopenghui/obsidian-language-learner#188]
最近更新是已经是1年多前了，想请问下这个是放弃开发了吗？
还想着要能支持多语言，能学习日语就好了。

**Comment by guopenghui** [comment]
因为我的身体原因，这段时间没有精力使用这个插件学英语。如果一个插件不是自己在使用，就没办法看到开发的方向，所以很长时间没有动这个插件了。

不过也没有放弃开发的意思。 可能后面恢复精力，重新开始语言学习时，会继续开发。

可以看一下 Pull request 那里，有几位作者fork后添加了自己的功能，可以先问问他们有没有支持多语言的计划，用他们发布的版本。
就像上面说的，目前我没有精力使用这个插件，不清楚未来开发方向，所以这些PR我也没有精力审核和合并，不过看起来实现了很多不错的功能，可以看看

**Comment by DreamAfar** [comment]
> 因为我的身体原因，这段时间没有精力使用这个插件学英语。如果一个插件不是自己在使用，就没办法看到开发的方向，所以很长时间没有动这个插件了。
> 
> 不过也没有放弃开发的意思。 可能后面恢复精力，重新开始语言学习时，会继续开发。
> 
> 可以看一下 Pull request 那里，有几位作者fork后添加了自己的功能，可以先问问他们有没有支持多语言的计划，用他们发布的版本。 就像上面说的，目前我没有精力使用这个插件，不清楚未来开发方向，所以这些PR我也没有精力审核和合并，不过看起来实现了很多不错的功能，可以看看

非常抱歉，看来是我误会了，还以为已经放弃了呢。
确实是身体健康更重要，非常感谢您对这个插件的开发，插件非常不错的。
祝您早日康复，元气满满每一天！加油💪
