### ISSUE TITLE
下载解压了但是没有main.js文件以及Failed toload plugin"obsidian-language- learner

### ISSUE THREAD

**Issue by 2932842805** [guopenghui/obsidian-language-learner#194]
![image](https://github.com/user-attachments/assets/12614b9d-c808-4078-a057-db602793d01a)
![image](https://github.com/user-attachments/assets/9a493eba-06f8-4013-be1c-2333e36ee982)
用的最新版本

**Comment by 2932842805** [comment]
release中有main.js文件  下载放入就好了    这好像是一个很基础简单的问题却难住我了  ,  可能我这个废物需要人生一站式解决方案  不过这个方案只能由自己建立验证,

**Comment by guopenghui** [comment]
我不太清楚原因，release那里的压缩包里面一直是有 `main.js` 的。但是偶尔也会有人来反映插件无法打开，没有这个文件

![image](https://github.com/user-attachments/assets/308153f4-61ce-46b9-8715-1887af37422c)
