### ISSUE TITLE
插件和Ob 1.7版本不兼容

### ISSUE THREAD

**Issue by 3217333857** [guopenghui/obsidian-language-learner#195]
TypeError:this.view.addAction is not a function
报错如上，不能开language-learner，不然进不去Ob

**Comment by honnys** [comment]
query selector all是嘛

**Comment by 1127633258** [comment]
我也是query selector all，只能进入安全模式重开

**Comment by hjm7** [comment]
不写前端, 但是把plugin.ts这个文件那几行注释掉然后重新build,用生成的main.js替换obsidian这个插件目录原本的main.js就行了
![image](https://github.com/user-attachments/assets/7d80ba21-d98b-4c94-95f0-adb3caf5744d)

**Comment by hjm7** [comment]
> > 不写前端, 但是把plugin.ts这个文件那几行注释掉然后重新build,用生成的main.js替换obsidian这个插件目录原本的main.js就行了 ![image](https://private-user-images.githubusercontent.com/39809764/377816780-7d80ba21-d98b-4c94-95f0-adb3caf5744d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNDg3MzMsIm5iZiI6MTcyOTI0ODQzMywicGF0aCI6Ii8zOTgwOTc2NC8zNzc4MTY3ODAtN2Q4MGJhMjEtZDk4Yi00Yzk0LTk1ZjAtYWRiM2NhZjU3NDRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDEwNDcxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4ODZkMGZlN2YxOTU3ZDBlZTIzNWRlYWI5NGYwNzEyM2I2NjhiMjgwMTAxNjQxOGJiZmI5ZGY2OTE2YTViNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qWmPQqiPO8jS5Yetuks5LanqPRmQvFi6E7Bb4bpjpgw)
> 
> 感谢大佬，但是不知道这个plugin.ts文件在哪呢，没找到，可不可以分享修改后的文件呢

把源码下到本地就有啊, src/plugin.ts, 不自己build就解压这个替换整个文件夹
[obsidian-language-learner.zip](https://github.com/user-attachments/files/17434929/obsidian-language-learner.zip)

**Comment by hjm7** [comment]
> > 不写前端, 但是把plugin.ts这个文件那几行注释掉然后重新build,用生成的main.js替换obsidian这个插件目录原本的main.js就行了 ![image](https://private-user-images.githubusercontent.com/39809764/377816780-7d80ba21-d98b-4c94-95f0-adb3caf5744d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNDg3MzMsIm5iZiI6MTcyOTI0ODQzMywicGF0aCI6Ii8zOTgwOTc2NC8zNzc4MTY3ODAtN2Q4MGJhMjEtZDk4Yi00Yzk0LTk1ZjAtYWRiM2NhZjU3NDRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDEwNDcxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4ODZkMGZlN2YxOTU3ZDBlZTIzNWRlYWI5NGYwNzEyM2I2NjhiMjgwMTAxNjQxOGJiZmI5ZGY2OTE2YTViNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qWmPQqiPO8jS5Yetuks5LanqPRmQvFi6E7Bb4bpjpgw)
> 
> 感谢大佬，但是不知道这个plugin.ts文件在哪呢，没找到，可不可以分享修改后的文件呢

把源码下到本地就有啊, src/plugin.ts, 不自己build就解压这个替换整个文件夹
[obsidian-language-learner.zip](https://github.com/user-attachments/files/17434929/obsidian-language-learner.zip)

**Comment by 3217333857** [comment]
> > > 不写前端, 但是把plugin.ts这个文件那几行注释掉然后重新build,用生成的main.js替换obsidian这个插件目录原本的main.js就行了 ![image](https://private-user-images.githubusercontent.com/39809764/377816780-7d80ba21-d98b-4c94-95f0-adb3caf5744d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNDg3MzMsIm5iZiI6MTcyOTI0ODQzMywicGF0aCI6Ii8zOTgwOTc2NC8zNzc4MTY3ODAtN2Q4MGJhMjEtZDk4Yi00Yzk0LTk1ZjAtYWRiM2NhZjU3NDRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDEwNDcxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4ODZkMGZlN2YxOTU3ZDBlZTIzNWRlYWI5NGYwNzEyM2I2NjhiMjgwMTAxNjQxOGJiZmI5ZGY2OTE2YTViNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qWmPQqiPO8jS5Yetuks5LanqPRmQvFi6E7Bb4bpjpgw)
> > 
> > 
> > 感谢大佬，但是不知道这个plugin.ts文件在哪呢，没找到，可不可以分享修改后的文件呢
> 
> 把源码下到本地就有啊, src/plugin.ts, 不自己build就解压这个替换整个文件夹 [obsidian-language-learner.zip](https://github.com/user-attachments/files/17434929/obsidian-language-learner.zip)

谢谢大佬，但是你这版插件，没办法开启阅读模式了，那个阅读模式的按钮没了，那插件不就没用了

**Comment by hjm7** [comment]
> > > > 不写前端, 但是把plugin.ts这个文件那几行注释掉然后重新build,用生成的main.js替换obsidian这个插件目录原本的main.js就行了 ![image](https://private-user-images.githubusercontent.com/39809764/377816780-7d80ba21-d98b-4c94-95f0-adb3caf5744d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNDg3MzMsIm5iZiI6MTcyOTI0ODQzMywicGF0aCI6Ii8zOTgwOTc2NC8zNzc4MTY3ODAtN2Q4MGJhMjEtZDk4Yi00Yzk0LTk1ZjAtYWRiM2NhZjU3NDRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDEwNDcxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4ODZkMGZlN2YxOTU3ZDBlZTIzNWRlYWI5NGYwNzEyM2I2NjhiMjgwMTAxNjQxOGJiZmI5ZGY2OTE2YTViNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qWmPQqiPO8jS5Yetuks5LanqPRmQvFi6E7Bb4bpjpgw)
> > > 
> > > 
> > > 感谢大佬，但是不知道这个plugin.ts文件在哪呢，没找到，可不可以分享修改后的文件呢
> > 
> > 
> > 把源码下到本地就有啊, src/plugin.ts, 不自己build就解压这个替换整个文件夹 [obsidian-language-learner.zip](https://github.com/user-attachments/files/17434929/obsidian-language-learner.zip)
> 
> 谢谢大佬，但是你这版插件，没办法开启阅读模式了，那个阅读模式的按钮没了，那插件不就没用了

我知道会去掉一个按钮, 但是我一般键盘操作,这个插件我只用翻译部分, 都没在意去的按钮在哪

**Comment by gitcpy** [comment]
![image](https://github.com/user-attachments/assets/e6cbd0f7-5937-45b2-9cc1-8de1ec07f698)
报错啦，麻烦有时间看看，感谢

**Comment by guopenghui** [comment]
更新至 0.2.6

**Comment by 330322919** [comment]
大佬关键时刻复活了

**Comment by gitcpy** [comment]
> 更新至 0.2.6

感谢🙏🙏🙏🙏🙏🙏🙏
