### ISSUE TITLE
Spaced Repetition这个复习的插件，单词没有发音功能了，这个怎么处理。应用环境obsidian1.7.4 插件Spaced Repetition 1.13.2

### ISSUE THREAD

**Issue by Githubxz07** [guopenghui/obsidian-language-learner#200]
![image](https://github.com/user-attachments/assets/9dfc54f1-ce0a-47ee-8470-f2aa2e282be5)
Spaced Repetition这个复习的插件，单词没有发音功能了，这个怎么处理。
应用环境obsidian1.7.4 插件Spaced Repetition 1.13.2

**Comment by guopenghui** [comment]
查看 `0.2.7`
