### ISSUE TITLE
新版obsidian音频播放不了（已解决）

### ISSUE THREAD

**Issue by liweibiao** [guopenghui/obsidian-language-learner#202]
[1.28起删除了对 URL 的支持`app://local`](https://obsidian.md/changelog/2023-05-03-desktop-v1.2.8/)
obsidian-language-learner依赖`app://local`插件中的功能，langr-audio字段的音频无法播放，则应使用`vault.getResourcePath(file: TFile)`和`vault.adapter.getResourcePath(vaultPath: string)`作为替代。

main.js中搜langr-audio

将
```c
["langr-audio"]||"";u&&u.startsWith("~/")&&(u=(dm.Platform.isDesktopApp?"app://local/":"http://localhost/_capacitor_file_")+o.constants.basePath+u.slice(1))
```

替换成
```c
["langr-audio"]||"";if(u&&u.startsWith("~/")){const file=o.app.vault.getAbstractFileByPath(u.slice(2));u=file instanceof TFile?o.app.vault.getResourcePath(file):o.app.vault.adapter.getResourcePath(u.slice(2));}
```

替换好才可以正常播放了

**Comment by DavidZhao2017** [comment]
这样替换好后，又不能播放本地音频了。有没有既能播放网络音频又能播放本地音频的办法？

**Comment by liweibiao** [comment]
@DavidZhao2017 
```
c=u["langr-audio"]||"";c&&(c.startsWith("http://") || c.startsWith("https://"))?c=c:c=o.app.vault.adapter.getResourcePath(c)
```
网络路径：langr-audio: http://example.com/audio.mp3
本地路径：langr-audio: Assets/audio.mp3

**Comment by Xu010106** [comment]
为什么还是不能播放啊？
![image](https://github.com/user-attachments/assets/e7e3273a-d706-4454-9365-b50aed6d35df)
![image](https://github.com/user-attachments/assets/f137c77d-3b0b-4f03-9fe9-8d4907a4b479)
还是播放不了，我下的是0.2.6的

**Comment by guopenghui** [comment]
查看 `0.2.7`
