### ISSUE TITLE
相对路径还是不会写...

### ISSUE THREAD

**Issue by Langzhousimawin** [guopenghui/obsidian-language-learner#208]
如图
![image](https://github.com/user-attachments/assets/14d224e5-71f2-4c96-93e1-1005b2824fc0)
绝对位置可用但相对位置死活不行
谢谢大佬指教

**Comment by guopenghui** [comment]
前面加个`~/`

**Comment by Langzhousimawin** [comment]
谢谢大佬❤️❤️❤️
