### ISSUE TITLE
可以为"打开为阅读模式"增加一个快捷键吗

### ISSUE THREAD

**Issue by WouiTC** [guopenghui/obsidian-language-learner#21]

**Comment by guopenghui** [comment]
巧了，今天刚把这个功能做出来😏

我再整理一下看看还有啥要改的，写一下文档之类的，今天晚上发出来

**Comment by guopenghui** [comment]
![image](https://user-images.githubusercontent.com/13451866/191476467-80a40af8-b51a-4e3b-88ba-1e05caf802da.png)

![image](https://user-images.githubusercontent.com/13451866/191476537-a828ab9d-9f1b-4311-b173-e7198e680b31.png)
