### ISSUE TITLE
自动勾选表达的类别

### ISSUE THREAD

**Issue by WouiTC** [guopenghui/obsidian-language-learner#22]
通过判断 "表达输入框" 中选择的是单词或是短语 ( 例如通过单词间是否含有空格来识别是否是短语， **注:** 忽略行首和行尾的空格 ) 来**自动勾选类别** (单词，短语)

**Comment by guopenghui** [comment]
在下次更新时实现

**Comment by guopenghui** [comment]
`0.1.0`版本中已更新
