### ISSUE TITLE
希望支持更改文章字体、格式以及自定义词典

### ISSUE THREAD

**Issue by Zwzs1** [guopenghui/obsidian-language-learner#24]
你好，感谢作者设计这款插件。目前用下来有两点建议:
1. 希望可以优化一下文章的阅读体验。
插件的阅读模式的字体太小了，换行和原文不一样。
![image](https://user-images.githubusercontent.com/83700563/192082145-f4277499-3f87-45a7-80ca-a54a5c63f62f.png)
没有 ob 原来的阅读模式看着舒服。
![image](https://user-images.githubusercontent.com/83700563/192082200-f57cf2c8-8a41-4d71-810d-8fad87c301af.png)
2. 希望能添加自定义词典。比如像Calibre 这样自建搜索源。或者支持导入本地词典。
![image](https://user-images.githubusercontent.com/83700563/192082636-41b39cd6-7275-407c-88d5-6faa1f490d90.png)

**Comment by guopenghui** [comment]
感谢建议。

换行现在是原文里面段与段之间要显式空一行，然后阅读模式里面才会分开。

**Comment by WouiTC** [comment]
@EriceVoi 可以将英语分段，增加空行，同时可以修改 css 样式，实现两端对齐

- ![image](https://user-images.githubusercontent.com/81695801/192128815-005a49ce-3395-45d6-a309-8becb54e2bf1.png)

- ![image](https://user-images.githubusercontent.com/81695801/192128819-885ce5a5-651c-4084-a3e0-260525237f02.png)

**Comment by guopenghui** [comment]
设置阅读模式字体和大小功能已在`0.2.0`实现，自定义词典的讨论转移至 #56
