### ISSUE TITLE
添加新单词面板中修改单词后，复习数据库中不是更新而是重复添加

### ISSUE THREAD

**Issue by outlierr** [guopenghui/obsidian-language-learner#26]
![1664689456117](https://user-images.githubusercontent.com/103714900/193439879-ce97046e-9f76-4a26-ba5c-9a664cc48990.png)
如图，修改一个单词后提交 复习文件夹中不是更新而又添加了相同的单词
![image](https://user-images.githubusercontent.com/103714900/193439915-143df93a-390b-4098-a212-60837f5b6639.png)
导致复习k卡片中会有两个相同的单词

**Comment by guopenghui** [comment]
在 e302114bf6ee1e09838a2bf41234acfd62719cdf 中实现了该功能

**Comment by aybeex** [comment]
大佬：你采用了重新合并复习数据方式，避免了同一个单词重复添加的缺点。但是，每个单词的学习记录没有了。
![image](https://user-images.githubusercontent.com/115936461/199364814-8932a860-a529-4ee7-a920-965965941f4d.png)
上图中，只有一个单词是新加的。其他的的，只要一刷新，又出现了。
