### ISSUE TITLE
阅读模式能否优化下中英对照的文章

### ISSUE THREAD

**Issue by grisbear** [guopenghui/obsidian-language-learner#27]
![1665039287120](https://user-images.githubusercontent.com/74553083/194234455-2325e3b2-6b62-4e4f-b281-c7f52ea091ab.png)

不知道是否有相关设置

**Comment by grisbear** [comment]
> 现在不支持，因为当前的英文分词实现技术不支持中文

进入阅读模式后，隐藏中文内容，或者禁止中文取词

**Comment by cyddgh** [comment]
> 进入阅读模式后，隐藏中文内容，或者禁止中文取词

请问这要如何操作，可以提供一个截图吗？我在设置或者阅读模式下没有看到。已经升级到0.1了。另外，新版本的分页功能很赞。

**Comment by guopenghui** [comment]
[main-过滤中文 .zip](https://github.com/guopenghui/obsidian-language-learner/files/9846901/main-.zip)

暂时可以替换这个来使用，后面加到下次更新里面

![_EKIM`{2DJPZWY`HE6ZY6L1](https://user-images.githubusercontent.com/13451866/197400837-ba872cbf-6674-4f09-837c-26871228de82.png)
