### ISSUE TITLE
obsidian更新1.0.0，需注意插件在1.0.0中的适配

### ISSUE THREAD

**Issue by DTIM001** [guopenghui/obsidian-language-learner#28]
我的obsidian今天自动更新到1.0.0了，发现language learner切换为阅读界面的图标不见了。
提个建议，目前插件版本功能已经初具雏形，而且很有用处。可以先适配最新的obsidian版本后，再进行功能扩展

**Comment by guopenghui** [comment]
感谢建议！

我试了一下在1.0.0版本下那个按钮也是能出来的，标签栏右键菜单里的选项进入阅读模式然后再退出，应该就出来了。
现在这个按钮出现的机制还不太稳定，后面我再调整一下

**Comment by DTIM001** [comment]
好嘞，加油哟

**Comment by ly5902534** [comment]
这个需要紧急修复啊，我这安装好就没出现过，原来是跟不上版本的原因啊，底层框架没建好吧！

**Comment by guopenghui** [comment]
> 这个需要紧急修复啊，我这安装好就没出现过，原来是跟不上版本的原因啊，底层框架没建好吧！

不是版本原因，在菜单这里打开一下，然后返回就有了。
![image](https://user-images.githubusercontent.com/13451866/195878271-a247312f-4f0b-42c4-93c2-863edb74a77e.png)


不能稳定出现是因为加这个按钮得在obsidian内置的markdownView对象上面做修改（这个类是内置的，不是我写的，不受我的控制，只能后期在上面修改）。 

修改的时机现在还没找好，所以偶尔会出不来，有时却能出来好几个。。。 

但是菜单这里是稳定的

**Comment by DTIM001** [comment]
**在更新前**，按钮不稳定出现的情况我也遇到了，之后发现菜单栏里可以稳定出现。
_**但是**_，
在更新之后，菜单栏里已经无法正常显示了
![Snipaste_2022-10-15_06-01-39](https://user-images.githubusercontent.com/113022813/195950722-34f71f72-b72a-4e81-a283-dffe2f76d980.png)

**Comment by ly5902534** [comment]
可能是我安装插件的时候就已经是新的obsidian版本了，所以安装插件后就没看到过阅读模式，很苦恼。这个不是稳不稳定，时隐时现的问题，而是菜单里就没有见到过，换笔记和重新进obsidian都不出现。我觉得还是有必要建立一个qq群，大家互助，而不是占用您的精力随时回答，可以找个空闲时间统一答复没解决的问题，这样更及时高效。虽然总体来说，这几个插件设置和使用并不算复杂。

**Comment by aybeex** [comment]
使用不同的主题，结果不同。我试了一下，minimal主题，在左侧边栏没有图标和右侧栏，没有图标。但是，相对应的位置可以点击。其他的主题，在左边不能点击。

**Comment by DTIM001** [comment]
我找到问题所在了：在obsidian的 “外观”设置选项中，有一个“show tab title bar”,打开后就可以出现按钮了。整个使用环境的适配还是有点不完善
