### ISSUE TITLE
求大佬能写一个具体的安装教程吗？

### ISSUE THREAD

**Issue by zgssbtl** [guopenghui/obsidian-language-learner#3]
自行构建那个，下载源码啥的看不懂，不会装啊😭😭😭

**Comment by zgssbtl** [comment]
![Inked屏幕截图 2022-06-01 193901_LI](https://user-images.githubusercontent.com/62315563/171547164-e9227daa-aa39-4ab2-855b-6bf3000b82ec.jpg)
![Inked屏幕截图 2022-06-01 193841_LI](https://user-images.githubusercontent.com/62315563/171547168-d040d014-d77f-4472-9838-13c49a34e0e9.jpg)
这些路径是在哪儿？我的插件设置上没有这些路径

**Comment by zgssbtl** [comment]
<img width="252" alt="屏幕截图 2022-06-02 114741" src="https://user-images.githubusercontent.com/62315563/171549358-913c1a67-866a-4776-9f63-5c600e086791.png">
**### 这个怎么回事？如何添加lingq/words_database.md文件路径类的？**

**Comment by guopenghui** [comment]
不是照抄，是自己建立一个md文件，然后把这个文件的路径写在设置里面。 比如你在`aaa`文件夹下建立了一个笔记`bbb`，那么这个路径就是`aaa/bbb.md`

**Comment by guopenghui** [comment]
可以参考readme中提到的视频教程，有从头安装和配置的过程
