### ISSUE TITLE
插件解析时 article word note 的顺序不能更换

### ISSUE THREAD

**Issue by DTIM001** [guopenghui/obsidian-language-learner#30]
我在完成阅读后需要做笔记并排版，试着切换了一下 “^^^word” 和 “^^^note” 的位置，"^^^note"也会出现在阅读界面
![Snipaste_2022-10-18_12-34-57](https://user-images.githubusercontent.com/113022813/196336534-187c4399-29e0-4c0f-aff1-c0f88c02197e.png)
我希望可以任意改变 “^^^article” “^^^words” ”^^^notes“的布局。
不知道这个issue是否可以纳入考虑呢？

**Comment by guopenghui** [comment]
已经实现，下次更新时实装

**Comment by guopenghui** [comment]
`0.1.0`版本中已更新

**Comment by DTIM001** [comment]
酷
