### ISSUE TITLE
没搞懂^^^words有什么作用，本篇读的也没归类到word下呀，是我弄的不对么？

### ISSUE THREAD

**Issue by shoudeyunkaijianyueming** [guopenghui/obsidian-language-learner#31]
如题，希望像note一样有归类

**Comment by shoudeyunkaijianyueming** [comment]
而且^^^words还是会出现在阅读里面
<img width="854" alt="image" src="https://user-images.githubusercontent.com/71814666/197330644-81e2354c-6f56-4e24-91c1-308e02457dd6.png">

**Comment by guopenghui** [comment]
能提供一下原文吗，`0.1`版里面应该不会把words打印出来了，我看看是什么问题。

words本意是能够直接查看本篇内学过的单词。但是具体该以什么格式去展示，以及怎么运用还没想好，所以这个模块暂时还没有做。

**Comment by shoudeyunkaijianyueming** [comment]
<img width="482" alt="image" src="https://user-images.githubusercontent.com/71814666/197369077-9e17aa54-31fd-47a4-a369-eaf12c4e3933.png">

**Comment by shoudeyunkaijianyueming** [comment]
例句好像可以放在extra部分https://www.reddit.com/r/ObsidianMD/comments/mhr4mz/obsidian_to_anki_using_the_extra_field_with/

**Comment by shoudeyunkaijianyueming** [comment]
这是obsidian to anki正则的说明https://github.com/Pseudonium/Obsidian_to_Anki/wiki/Regex

**Comment by shoudeyunkaijianyueming** [comment]
当然这仅是建议，还是期待大佬word部分的完善

**Comment by shoudeyunkaijianyueming** [comment]
感谢作者
