### ISSUE TITLE
为什么复习.md都有一个问号？

### ISSUE THREAD

**Issue by ly5902534** [guopenghui/obsidian-language-learner#32]
1.如题
2.单词每提交一次就是一个新段落，不能在同一个词里面更新吗？
3.有脚注的话阅读模式就不适合阅读了，当然插件跟obs本身是一样的。使用插件的前提不一样，适合纯文本，而不是一篇有笔记的文章
4.阅读模式能增加点击单词显示单词笔记或查词面板吗？
谢谢

**Comment by guopenghui** [comment]
1. 问号应该是题目和答案的分隔符吧，SpacedRepetition这个插件用的
2. 当前的增量更新机制下不行，也许后面会改
3. 脚注里写的东西很多的话可能显示上就比较乱了
4. 可以。但是直接点左边的按钮好像也不麻烦

**Comment by guopenghui** [comment]
第2条最新版本已经实现了在复习数据库中同一词内更新
第3条属于提升阅读体验，合并在 #5 来讨论
第4条建议单独提一条issue来具体讨论
