### ISSUE TITLE
obsidian1.0.0版本 插件0.1.0版本   单词数据库更新的单词异常

### ISSUE THREAD

**Issue by cycy12356** [guopenghui/obsidian-language-learner#33]
版本更新后，单词复习数据库中每个单词间隔太近了，需要我手动分开，，
![image](https://user-images.githubusercontent.com/104835060/197663482-47a965d7-0ce7-4725-8bec-119b200207d1.png)
应该如下图所示
![image](https://user-images.githubusercontent.com/104835060/197663721-beb59c9d-94c3-4d44-bb39-b066456d74af.png)

**Comment by guopenghui** [comment]
了解，我多加一行空行

**Comment by guopenghui** [comment]
在 e302114bf6ee1e09838a2bf41234acfd62719cdf 中解决
