### ISSUE TITLE
obsidian1.0.0版本 插件0.1.0版本 文章读完后消失了

### ISSUE THREAD

**Issue by cycy12356** [guopenghui/obsidian-language-learner#34]
![image](https://user-images.githubusercontent.com/104835060/197667750-a2b4871f-5c8b-4dd9-9fc6-88aa9e5198ed.png)
![image](https://user-images.githubusercontent.com/104835060/197667783-efbf6c36-2edf-4cc8-8b09-3aa03dcabf7b.png)

**Comment by guopenghui** [comment]
好不好复现呀，能不能提供一下这篇文档？我还没遇到过这个问题。。

还有读文章时有没有进行其他的什么操作？

**Comment by cycy12356** [comment]
[Day of the Dragon King - Mary Pope Osborne.md](https://github.com/guopenghui/obsidian-language-learner/files/9869331/Day.of.the.Dragon.King.-.Mary.Pope.Osborne.md)
就是这两篇文章
在读文章时，我还打开了单词复习数据库给单词之间加空格

**Comment by guopenghui** [comment]
如果仍有问题，请提供能稳定复现的原始文档，重新打开issue
