### ISSUE TITLE
切换color theme时，new word padel不会跟随切换配色方案

### ISSUE THREAD

**Issue by StanHustler** [guopenghui/obsidian-language-learner#35]
> Obsidian: 1.0.0
> obsidian-language-learner: 0.1.0
> OS: macOS Monterey 12.5.1

因为color theme设置为跟随系统所以经常会切换light/dark，在自动切换的过程中，左边的Search padel很舒服，但是右边的new word padel每次都需要关闭重开后才能适配当前主题色，下面是问题截图

![Screen Shot 2022-10-27 at 11 53 59](https://user-images.githubusercontent.com/62613346/198187578-71a6285c-334d-4ce1-849a-501ca9b59e79.png)
![Screen Shot 2022-10-27 at 11 49 54](https://user-images.githubusercontent.com/62613346/198187602-637b325a-9268-4c6d-9845-c85d45f32633.png)

**Comment by guopenghui** [comment]
其实Search panel也是一样的，切换深色/浅色的时候上面的按钮和输入框颜色也不会自动变化。
![image](https://user-images.githubusercontent.com/13451866/198257585-0f3061a2-2f0a-45c4-8632-b01ea5c195bc.png)


这个是因为插件用的ui库naive-ui是通过一个js变量来控制深色/浅色模式，但是ob没有提供监测模式变化的方法，所以ob变了模式后插件是没办法知道的。 
同时切换深浅模式也是一个低频操作，也不值得专门浪费性能不停地检查模式。 所以这个问题暂时没有完美的解决办法，看ob后面会不会提供相关的api吧。
