### ISSUE TITLE
复习卡片界面不适配

### ISSUE THREAD

**Issue by G-jiajian** [guopenghui/obsidian-language-learner#36]
up主你好，我按照你的视频步骤，但复习卡片界面和你不一样，请问有什么办法修改吗，感觉我的界面很难复习
![image](https://user-images.githubusercontent.com/102669298/198608766-4cfb127e-ac7f-4ed1-82f8-c5733b379a86.png)
![image](https://user-images.githubusercontent.com/102669298/198609224-b2856cf5-a086-4e73-80d9-24691f8bcd59.png)

**Comment by guopenghui** [comment]
看一下你复习数据库（笔记）里面transfer那一块是什么样的？

**Comment by G-jiajian** [comment]
![image](https://user-images.githubusercontent.com/102669298/198823205-c659d034-286f-4705-8903-2a7fac0e16c5.png)
我不知道是哪个步骤错了

**Comment by guopenghui** [comment]
看起来没什么问题，按理来说在这里有换行，复习界面也应该是换行的。 

把spaced repetition插件的设置重置一下，或是换个主题试试。

**Comment by guopenghui** [comment]
如果仍存在问题，请打开控制台查看一下复习面板的样式发过来，重新打开issue
![image](https://user-images.githubusercontent.com/13451866/204072627-cc456bd3-f1c7-448e-9825-96bce3218617.png)
