### ISSUE TITLE
希望在演讲模块支持本地音频

### ISSUE THREAD

**Issue by ChancellorNG** [guopenghui/obsidian-language-learner#37]
不知道是不是我技术不熟练，无法在演讲那个模块引入本地音频，只能找网上.mp3后缀的网页。

**Comment by guopenghui** [comment]
添加本地音频路径时要按照这样的格式：
`langr-audio: app://local/文件地址`

比如：`langr-audio: app://local/C:/User/music.mp3`

**Comment by ChancellorNG** [comment]
> ![image](https://user-images.githubusercontent.com/13451866/199034569-31da093c-613f-4805-ac4e-934647b487e4.png)
> 
> ![image](https://user-images.githubusercontent.com/13451866/199034637-d52e8169-b712-4765-b8e1-d73ad19d0000.png)

感谢您的及时解答！
