### ISSUE TITLE
能否修改阅读视图下的字体大小

### ISSUE THREAD

**Issue by cyddgh** [guopenghui/obsidian-language-learner#38]
发现进入插件的阅读视图后，字体比较小，而且不能依靠ob的主题设定进行调整。能否增加这一功能，或者提供几类字体大小以供选择。

**Comment by nerd010** [comment]
可以在插件的 styles.css 文件中的 `langr-reading` 中添加 `font-size`, 来调整。如

```
#langr-reading {
    user-select: none;
    line-height: 1.8em;
    font-family: 'Times New Roman';
    font-size: 32px;
}
```

字体大小按自己的需要调整就好。

效果图：

<img width="1628" alt="Screen Shot 2022-11-04 at 11 59 02" src="https://user-images.githubusercontent.com/12123295/199882669-cf666daa-c2f5-4388-bb08-b819d78d0b92.png">

---

调整后重新打开一下 Obsidian，查看一下文章中原来写好的 langr 插件需要的格式 `^^^article, ^^^words, ^^^notes` 是否完整，
我用命令刷新了一下 单词数据库（Word Database）和 复习数据库（Review Database）。这样就可以正常使用了。

先用着，手动调整的功能等作者更新吧~

PS：插件的位置在隐藏文件夹 `.obsidian` 中。

**Comment by cyddgh** [comment]
谢谢，目前已经按照修改CSS完成调整了。

**Comment by guopenghui** [comment]
此功能已在`0.2.0`中实现
