### ISSUE TITLE
复习单词的记录没有了

### ISSUE THREAD

**Issue by aybeex** [guopenghui/obsidian-language-learner#39]
大佬：复习单词的功能，采用了重新合并的方式，而不是添加的方式。很好，避免的统一单词重复的添加。但是，原来的学习记录没有了。
![image](https://user-images.githubusercontent.com/115936461/199365200-d4f79b10-f7ab-4cf8-89c9-0e53b81de741.png)

以上的的单词，只有一个是新加了。其他的，只要一刷新，有重新出现了。

**Comment by guopenghui** [comment]
是本来有128个单词，0个新单词，0个已到期单词， 然后添加了一个新单词后，变成了31个新单词吗？

能不能提供一个复习记录会消失的单词的记录给我，就是从`#word`一直到最后的`<!--SR...-->`。 有可能是现在的正则表达式没识别出来这个记录

**Comment by aybeex** [comment]
![image](https://user-images.githubusercontent.com/115936461/199456957-0778538f-a631-4f62-b9e4-359184dcdcec.png)

**Comment by aybeex** [comment]
我发现，你是不是把<>的时间标示入库了。怎么，很多的单词，没有这个标示了呢？

**Comment by aybeex** [comment]
![image](https://user-images.githubusercontent.com/115936461/199460266-fae4cd06-54d1-4f7d-8a08-31a49a7cf0b4.png)

**Comment by guopenghui** [comment]
[main.zip](https://github.com/guopenghui/obsidian-language-learner/files/9919959/main.zip)

替换一下`main.js`文件
应该是正则的问题，`\w`不包括空格，导致所有的词组都没有识别出来，所以词组的复习记录消失了。
https://github.com/guopenghui/obsidian-language-learner/blob/a6ed7e15899f5fb73b85a10f0bbd1f7779b3c8cb/src/plugin.ts#L216

**Comment by aybeex** [comment]
大佬，你更新一下你的程序。你的用户已经不少了。

**Comment by aybeex** [comment]
![image](https://user-images.githubusercontent.com/115936461/199485521-70f6cf18-7fa1-4946-b618-3a3b7a4329e7.png)
大佬，还是不行。我先用你之前的版本。等你修好了，我再更新。

**Comment by guopenghui** [comment]
能否提供一个最小可复现的样本呢？ 比如新建一个数据库，然后添加一些单词，然后确定在某种条件下一定会发生这个现象。

把indexedDB数据库导出出来，发出来，我测试一下。

现在我没办法复现问题，也就没办法解决
