### ISSUE TITLE
Invalid database path

### ISSUE THREAD

**Issue by jqk** [guopenghui/obsidian-language-learner#40]
0.1.1两个有可能的bug，也有可能是我使用不对？

1）使用ob 1.0.3 版。创建空白的库，都使用默认设置，包括默认的库WordDB（也试过换一个名称并重启，但效果相同），可以标记单词，但是提交时，总是报 Invalid database path 错误，可实际上，单词都记录下来了，功能是正常的，就是每次，每次都报这个错误。

2）标记了6个新学生词，但统计中，给出的都是0。

还没继续尝试其它功能。

很好的插件，谢谢！

**Comment by guopenghui** [comment]
invalid database path 是因为没有设置单词数据库和复习数据库。 
0.1.0版更新后会在提交单词时自动刷新这两个数据库，如果没有在设置中设置路径的话就会报错。 之前是手动刷新的。这块的逻辑也许应该改一下，如果没设置就不刷新了，你可以暂时先把这两个路径设置上，暂时就不会报错了。
![image](https://user-images.githubusercontent.com/13451866/199641988-66947441-e322-4bd5-98b8-10d2f298daa8.png)

统计这里我还不太清楚是怎么回事，应该是会刷新的。重启后也是一样吗？

**Comment by jqk** [comment]
1）关闭自动刷新后，不再报错。但在哪里手动刷新呢？
2）填写两个文件名后，不再报错。但得手工先建文件，不会自己创建。
3）统计工作正常，我的问题，右侧没拉足够大，只显示到昨天，当然都是0。

感觉直接使用系统报错，稍显粗糙。但确实很棒了！

谢谢！后续使用会继续沟通。

**Comment by guopenghui** [comment]
手动刷新是用命令，`刷新单词数据库`和`刷新复习数据库`

填了文件名后就可以打开自动刷新了，方便一些

**Comment by wwjCMP** [comment]
这个bug修复了吗？填上文件名字，打开自动刷新还是报错哇。
