### ISSUE TITLE
添加多个词典供选择

### ISSUE THREAD

**Issue by nerd010** [guopenghui/obsidian-language-learner#41]
如题
现在只有“有道”的翻译，有一些词会显示没有结果。如果可以添加多个词典，这种情况就会越来越少或者没有了。

**Comment by nerd010** [comment]
看到之前有提到这个问题就关了

**Comment by guopenghui** [comment]
没事，可以开着，之前的都是很多建议混在一起，这个问题比较明确一些方便查看和讨论。

**Comment by guopenghui** [comment]
把其他一些词典也做进去不困难，现在我想的是应该怎么组织，是一次只允许选择其中的一个来用，还是说同时显示所有词典(或是选择的某一部分词典)的结果，就像沙拉查词那样。

**Comment by nerd010** [comment]
我是这么想的：
词典：
    - 第一次安装有一个默认的词典；
    - 在插件设置里可以让用户自己选择某一部分词典或全部词典。
查词：
    - 多个词典的话就只展开前一个或前两个的内容，其他的折叠起来；
    - 如果用户点击折叠起来的词典，可以展开显示词典的内容。

仅供参考，看你自己怎么想，哈哈

**Comment by wmings2020** [comment]
你这个插件做的太好了，思路清晰，方法简便，我会永远支持你；另外 希望增加的词典有选择性，或自定义用什么词典就最好了，毕竟每个人的习惯不同；还有就是根据你的思路，能否完善一下我们可以去学习古汉语或其他语言，只要是换个词典就可以实现的那种，谢谢作者！！！！继续完善！！

**Comment by guopenghui** [comment]
从`0.2.0`版开始增加了多词典支持，如果后面有其他建议的词典，可以单独发feature request
