### ISSUE TITLE
希望能有导出单词文本 & 文章分析功能

### ISSUE THREAD

**Issue by thehyrehy** [guopenghui/obsidian-language-learner#46]
非常感谢作者大大 我在lingq过期前几天发现了这款神级插件 基本覆盖了lingq的功能 使用起来非常方便
目前就是希望能加一个单词导的功能  在^^^WORDS 这个功能区里汇总了单词 但有点不太方便直接导出到其它背单词软件中 
下面是我使用不同手机阅读器app导出的单词
不知道这个功能在obsidian中好不好实现 只需要纯英文文本就能满足我的需求了
![image](https://user-images.githubusercontent.com/118100326/201512998-8ddd25b5-628a-4aef-b463-5cc9d8e67af6.png)
![image](https://user-images.githubusercontent.com/118100326/201513023-b9c23fe2-9aaa-4413-8607-530c5a343877.png)

在lingq中有这个自动分析当前文本新词、已知词汇数量和比例的功能 可以方便了解文本的难度 不知道能不能实现 
![image](https://user-images.githubusercontent.com/118100326/201513518-6ca0df75-f2bd-4dd4-9588-372b647803eb.png)

**Comment by guopenghui** [comment]
实现导出功能不难，关键是以什么样的格式导出。 之前也有人建议加个导出功能，但是不同人想要的格式都不一样，不好统一。可以在这个issue下讨论一下。

第二个功能挺好的，我试着做一下

**Comment by thehyrehy** [comment]
> 实现导出功能不难，关键是以什么样的格式导出。 之前也有人建议加个导出功能，但是不同人想要的格式都不一样，不好统一。可以在这个issue下讨论一下。
> 
> 第二个功能挺好的，我试着做一下

个人觉得白色那张表格（CSV格式的文件）比较万能吧，可以转化成很多格式。（像我这种用手机背词的，只需要英文文本的直接复制表格中英文那一列就ok  大部分手机背词app只要英文文本就可以导入单词本）
![image](https://user-images.githubusercontent.com/118100326/201519967-382e55c1-364f-40a7-9eba-a2986976a9f7.png)

然后CSV表格后面可以加单词含义，例句之类的

**Comment by guopenghui** [comment]
`0.2.0`版里设置面板上加了一个导出的按钮，是导出到剪切板。详见release说明。
