### ISSUE TITLE
阅读模式不显示内容

### ISSUE THREAD

**Issue by ly5902534** [guopenghui/obsidian-language-learner#47]
<img width="1083" alt="image" src="https://user-images.githubusercontent.com/61930853/202866966-5909ecdb-233f-44ab-96da-a6dcaa0a3905.png">
<img width="922" alt="image" src="https://user-images.githubusercontent.com/61930853/202866971-aaf830c8-3ce1-4c60-bea9-ac526b0bf448.png">

**Comment by guopenghui** [comment]
这篇文章能发给我看看吗，把md文档打个zip压缩包发过来我测试一下

**Comment by ly5902534** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "guopenghui/obsidian-language-learner"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月20日(星期天) 上午7:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [guopenghui/obsidian-language-learner] 阅读模式不显示内容 (Issue #47)





 
这篇文章能发给我看看吗，把md文档打个zip压缩包发过来我测试一下

**Comment by guopenghui** [comment]
直接在commnet里面发就行，回复邮件是收不到的。

**Comment by ly5902534** [comment]
[语言插件测试.md.zip](https://github.com/guopenghui/obsidian-language-learner/files/10049434/md.zip)

**Comment by guopenghui** [comment]
我这边显示是正常的。
![image](https://user-images.githubusercontent.com/13451866/202900676-67ed5f45-3928-47cb-8356-4efd2a1002b3.png)


你按`shift+ctrl+i`打开console（控制台），然后再对文章打开阅读模式，看看有没有什么报错信息
另外发一下你的插件设置，没有打开第一个`打开服务器`的设置吧，如果打开了就关掉

**Comment by ly5902534** [comment]
没问题了，不过这个需要记录很多单词，我可能还是会选择其他的方式。之后阅读难点可能会用这样的方式，忽略常见词，标记不认识的词。还是很感谢提供这种学习方式
