### ISSUE TITLE
一个bug，点击单词后学习新单词栏随机无反映，

### ISSUE THREAD

**Issue by mekefly** [guopenghui/obsidian-language-learner#52]
0.2.1单词随机点击不管用的bug，如果需要数据库去查找bug的话可以找我要一下，有1000多单词但不是什么重要的东西，从0.1.某版本更新上来的，之前没有bug的，我先回退一下试试

## 版本
- app: v1.0.3
- 安装程序版本：v0.15.9
- 插件版本: 0.2.1

## 样例
随机无反映，单词在1号位置点击能正常查询到，在2号位置点击就无反映，位置随机(至少没有发现规律)例图
![image](https://user-images.githubusercontent.com/64407174/203940364-2ce0938a-47d3-4ddd-9f7f-160942687244.png)
![image](https://user-images.githubusercontent.com/64407174/203940416-81d5758b-36f3-44b4-92e1-3877fe5d41c0.png)
![image](https://user-images.githubusercontent.com/64407174/203940599-bd941c06-b7fe-448a-8fcb-402cb86c56d6.png)
![image](https://user-images.githubusercontent.com/64407174/203940730-d3d18b2f-738f-4121-af0e-6d628d31a475.png)
有反映的重复点击依然有反映无反映的单词换页回来点击还是无反映，不管是新词还是老词都是这样的

**Comment by mekefly** [comment]
当版本回退到0.1.0时一切表现正常

手抖了不小心关了，咳

**Comment by guopenghui** [comment]
嗯，你把单词库导出一下，把json文件和这篇文章的md发到 `guo_peng_hui@163.com`这个邮箱吧，我试着复现一下

**Comment by iSuhgaL** [comment]
也有同样的问题，希望作者大大能够修复～

**Comment by mekefly** [comment]
> 嗯，你把单词库导出一下，把json文件和这篇文章的md发到 `guo_peng_hui@163.com`这个邮箱吧，我试着复现一下

已发送，请注意接收一下

**Comment by guopenghui** [comment]
大概是因为打开了例句自动翻译，但是你点的那个单词在代码里面，所以翻译获取失败导致报错了。
同样的，有时可能句子比较复杂，或者混杂了其他符号，机器翻译不过来，也会获取失败。 @iSuhgaL 
加了个异常处理，用这个替换`main.js`就好了：
[main.zip](https://github.com/guopenghui/obsidian-language-learner/files/10095578/main.zip)

**Comment by iSuhgaL** [comment]
正常了～谢谢您

**Comment by mekefly** [comment]
太好了表现正常

**Comment by mekefly** [comment]
> 大概是因为打开了例句自动翻译，但是你点的那个单词在代码里面，所以翻译获取失败导致报错了。 同样的，有时可能句子比较复杂，或者混杂了其他符号，机器翻译不过来，也会获取失败。 @iSuhgaL 加了个异常处理，用这个替换`main.js`就好了： [main.zip](https://github.com/guopenghui/obsidian-language-learner/files/10095578/main.zip)
谢谢您
