### ISSUE TITLE
0.20和0.2.1版本无法启用

### ISSUE THREAD

**Issue by DreamAfar** [guopenghui/obsidian-language-learner#53]
## 0.1.1版本是可以正常使用，按0.2.0的release说明安装更新了，但新版0.20和0.2.1版本在obsidian都无法启用
插件页面显示有安装插件，但是开启后，无法显示插件设置和相关的功能

![image](https://user-images.githubusercontent.com/69999980/203972731-2f85ec2e-0791-4228-aee8-58cca82ccbe7.png)
![image](https://user-images.githubusercontent.com/69999980/203972861-0a0d4226-43e0-4c51-9ec9-ec4dffacdc11.png)
![image](https://user-images.githubusercontent.com/69999980/203972955-e0d982b8-0dae-441b-bfb7-d27ee23378e6.png)

## 试了创建新的仓库，再重新安装也不行，退回0.1.1版本又是正常的
![image](https://user-images.githubusercontent.com/69999980/203974414-eb8be540-721d-46fa-baed-529aba777703.png)

**Comment by y000k** [comment]
是的，同样的问题。macos obsidian1.0.3。
启用插件时报错。
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'use_server')
    at GR.eval (plugin:obsidian-language-learner:1796:6318)
    at Generator.next (<anonymous>)
    at i (plugin:obsidian-language-learner:6:1102)

**Comment by guopenghui** [comment]
我知道原因了。 设置文件的读取方式有些问题，当文件夹不存在配置文件`data.json`的时候，读配置会出错导致插件加载失败，显示不出设置面板。
如果是之前文件夹里如果有`data.json`，就不会有问题。

解决办法是新建一个文本文件，里面填上一个`{}`，然后保存，改名为`data.json`，然后重启一下插件就好了
或是直接把这个解压到插件目录下：
[data.zip](https://github.com/guopenghui/obsidian-language-learner/files/10093264/data.zip)

**Comment by y000k** [comment]
> 我知道原因了。 设置文件的读取方式有些问题，当文件夹不存在配置文件`data.json`的时候，读配置会出错导致插件加载失败，显示不出设置面板。 如果是之前文件夹里如果有`data.json`，就不会有问题。
> 
> 解决办法是新建一个文本文件，里面填上一个`{}`，然后保存，改名为`data.json`，然后重启一下插件就好了 或是直接把这个解压到插件目录下： [data.zip](https://github.com/guopenghui/obsidian-language-learner/files/10093264/data.zip)

谢谢这么快并且有用的回复！

**Comment by DreamAfar** [comment]
> 我知道原因了。 设置文件的读取方式有些问题，当文件夹不存在配置文件`data.json`的时候，读配置会出错导致插件加载失败，显示不出设置面板。 如果是之前文件夹里如果有`data.json`，就不会有问题。
> 
> 解决办法是新建一个文本文件，里面填上一个`{}`，然后保存，改名为`data.json`，然后重启一下插件就好了 或是直接把这个解压到插件目录下： [data.zip](https://github.com/guopenghui/obsidian-language-learner/files/10093264/data.zip)

按照上述方法，插件可以正常加载了😄，感谢🙏🏻

**Comment by Gleaner2021** [comment]
> 我知道原因了。 设置文件的读取方式有些问题，当文件夹不存在配置文件`data.json`的时候，读配置会出错导致插件加载失败，显示不出设置面板。 如果是之前文件夹里如果有`data.json`，就不会有问题。
> 
> 解决办法是新建一个文本文件，里面填上一个`{}`，然后保存，改名为`data.json`，然后重启一下插件就好了 或是直接把这个解压到插件目录下： [data.zip](https://github.com/guopenghui/obsidian-language-learner/files/10093264/data.zip)

赞，确实是这个问题，感谢！
