### ISSUE TITLE
0.2.3，弹窗无法关闭

### ISSUE THREAD

**Issue by limrli** [guopenghui/obsidian-language-learner#65]
更新了0.2.3后，找不到查词的弹窗没有关闭的路径了。
![9DBB76BE0A98F5E2922EE3C04EC64156](https://user-images.githubusercontent.com/68333993/205689711-924c690e-afdf-4c55-824d-9fd7d0c62c1e.png)

**Comment by guopenghui** [comment]
> 更新了0.2.3后，找不到查词的弹窗没有关闭的路径了。
> ![9DBB76BE0A98F5E2922EE3C04EC64156](https://user-images.githubusercontent.com/68333993/205689711-924c690e-afdf-4c55-824d-9fd7d0c62c1e.png)
> 

什么是“找不到查词的弹窗没有关闭的路径”？没看懂这句话。

能发个截图吗，比如在哪种状态下关不了。一般是只要在弹窗外面点击就会关掉

**Comment by guopenghui** [comment]
可以试一下看`0.2.4`版还有没有这个问题

**Comment by limrli** [comment]
不好意思，没表达清楚。这个小窗怎么关闭啊？
![image](https://user-images.githubusercontent.com/68333993/206277178-38716f19-3865-4060-883b-ee5848f3c59e.png)

**Comment by limrli** [comment]
> 可以试一下看`0.2.4`版还有没有这个问题

ok了
![89822D38AB234E4A2EC1836C3E79B89E](https://user-images.githubusercontent.com/68333993/206277878-b4db581a-f060-470d-b43c-d74148b9198b.png)

**Comment by guopenghui** [comment]
不知道为什么github这里没显示你发的这个消息，今天看邮箱才看到

![image](https://user-images.githubusercontent.com/13451866/206824533-3fc91ffd-3bfa-4a47-ad34-cf76367d07c7.png)
![image](https://user-images.githubusercontent.com/13451866/206824562-beebab45-d93a-4d05-9602-09096e12572b.png)

关不掉是因为你点了小窗右上角的“置顶”按钮，所以关不掉。 平常模式下点击除新词面板的其他位置就可以关掉这个弹窗了。
