### ISSUE TITLE
弹出式查词面板关闭无效。

### ISSUE THREAD

**Issue by hello-sucess** [guopenghui/obsidian-language-learner#66]
<img width="863" alt="image" src="https://user-images.githubusercontent.com/31380144/205805474-68215495-d31e-4b18-b03f-df431d37dc70.png">
在设置中关闭了该功能，但是查词还是会弹出这个窗口。0.2.3版本
<img width="889" alt="image" src="https://user-images.githubusercontent.com/31380144/205805563-a59ea8c9-167c-491d-a05b-9335a305cc7e.png">

**Comment by guopenghui** [comment]
后面我改一下

**Comment by guopenghui** [comment]
`0.2.4`中解决
