### ISSUE TITLE
电脑上点击单词直接发音的问题，加一个设置开启和关闭

### ISSUE THREAD

**Issue by guopenghui** [guopenghui/obsidian-language-learner#69]
### Discussed in https://github.com/guopenghui/obsidian-language-learner/discussions/68

<div type='discussions-op-text'>

<sup>Originally posted by **nerd010** December 10, 2022</sup>
更新后，点击单词会直接发音，这个能不能有个开关负责开启和关闭？因为在公共场所没戴耳机就很突然，哈哈</div>

**Comment by xiuqiang1995** [comment]
同求。我也是没找到关闭自动朗读的功能。特别是翻译句子的时候，很尴尬。

**Comment by guopenghui** [comment]
见 `0.2.5`
