### ISSUE TITLE
一次添加两个例句时无限加载

### ISSUE THREAD

**Issue by Joel2561** [guopenghui/obsidian-language-learner#7]
测试发现，当使用学习新单词添加单词例句时，添加一个例句工作正常，然而一次性提交两个例句会卡住无限加载。先添加一个例句，然后更新为两个例句不会卡住，怀疑创建两个例句时提交数据的代码可能有隐性的 bug。
稳定复现。

**Comment by guopenghui** [comment]
已经找到问题，添加多个句子时，除最后一个句子以外的对象都会被转换成proxy（可能是用的naive-ui的行为），但是数据库存储必须用原对象而不是proxy，所以保存失败。   
![image](https://user-images.githubusercontent.com/13451866/172747029-fd43676d-1328-4caa-aa7c-e4b9b8625d51.png)


添加了一个转换过程，已解决这个问题，下次更新时修复。

**Comment by guopenghui** [comment]
`0.0.4`已发布

**Comment by Joel2561** [comment]
完美解决问题！
