### ISSUE TITLE
[Video] 使用影片介紹

### ISSUE THREAD

**Issue by emisjerry** [guopenghui/obsidian-language-learner#70]
我錄了一個教學影片，分別上傳到YouyTube和B站，希望能有更多人知道你的作品：

[Obs＃108] 用Obsidian學習英文：Language Learner—事半功倍的Obsidian外掛: https://www.youtube.com/watch?v=lK3oFpUg7-o
https://www.bilibili.com/video/BV1N24y1k7SL/

**Comment by guopenghui** [comment]
嗯，我昨天刷b站在首页刷到啦😁，讲解的很详细！

**Comment by guopenghui** [comment]
我后面改一下readme加上去

**Comment by guopenghui** [comment]
readme里面已添加
