### ISSUE TITLE
ob内置pdf阅读器，不能替换

### ISSUE THREAD

**Issue by cycy12356** [guopenghui/obsidian-language-learner#73]
我将pdf.zip解压到正确的位置了，重启obsidian后还是无法替换内置PDF阅读器
![Snipaste_2022-12-17_12-58-35](https://user-images.githubusercontent.com/104835060/208226034-6a5ea57d-eba8-44c6-bca2-58aebad931ed.png)
![Snipaste_2022-12-17_13-01-49](https://user-images.githubusercontent.com/104835060/208226038-e7260ddb-b2b2-4410-a1ca-9579e3b34a6c.png)
期望大佬解答下疑惑🥰

**Comment by guopenghui** [comment]
![image](https://user-images.githubusercontent.com/13451866/208239815-b090c66f-b9b9-4ce9-8743-1e9872af4cad.png)

和我当时写这个功能时一样，查了半天错不知道问题在哪里，最后发现是单词写错了😂
