### ISSUE TITLE
请求制作类似沙拉查词的css片段

### ISSUE THREAD

**Issue by sche11** [guopenghui/obsidian-language-learner#76]
我注意到新增了浮动的查词面板，这让我联想到了[沙拉查词](https://saladict.crimx.com/)，沙拉查词是一款浏览器的扩展，能够划词翻译，同时支持多个词典查询，并且支持生词添加到anki和欧路单词。
所以请求制作类似沙拉查词的css片段，统一样式。

**Comment by guopenghui** [comment]
统一样式是指界面和沙拉做成一样的吗？查词面板做的时候本身参考了很多沙拉的设计，但是外观没必要完全做成一样的吧，能实现需要的功能就行

**Comment by sche11** [comment]
> 统一样式是指界面和沙拉做成一样的吗？查词面板做的时候本身参考了很多沙拉的设计，但是外观没必要完全做成一样的吧

- 是的不需要一致，但沙拉查词作为一款成熟的浏览器扩展，有很多细节可以参考。
- 目前的面板辨识度还不够，比如词典名称和查询单词之间，当弹出查词面板时，我的第一眼是看到单词，然后就会被很小的词典名称干扰，类似发现屏幕上有根细小的头发。另外，词典名称和单词之间的空隙很大，会有一定的割裂感。
- 在沙拉查词里，词典前是有图标的，可以清晰的把词典和单词区分开来，先看到词典图标，了解需要着重的内容，比如英英就是着重用英语理解英语，词根就是着重不同词性、类别；接下来看到与之相邻的单词和释义就有清晰的着重点。
- 希望统一样式的另一个理由是，沙拉查词和obsidian-language-learner的样式很接近，如果样式差异比较大很容易区别，但长期使用沙拉查词，使得很不习惯obsidian-language-learner的查词面板，无法集中注意力。

>能实现需要的功能就行

[obsidian-language-learner](https://github.com/guopenghui/obsidian-language-learner/issues/76)依托于obsidian（拥有数量繁多的插件），希望能碰撞出更多的火花。

**Comment by guopenghui** [comment]
主要还是没有图标，因为ob插件没办法单独搞一个public目录放图标，后面我看看有没有办法把图标直接打包进main.js里面

**Comment by sche11** [comment]
> 主要还是没有图标，因为ob插件没办法单独搞一个public目录放图标，后面我看看有没有办法把图标直接打包进main.js里面

我看到在[Blue-topaz-examples](https://github.com/cumany/Blue-topaz-examples)的css片段[【图标】双链图标.css](https://github.com/cumany/Blue-topaz-examples/blob/main/.obsidian/snippets/%E3%80%90%E5%9B%BE%E6%A0%87%E3%80%91%E5%8F%8C%E9%93%BE%E5%9B%BE%E6%A0%87.css)中使用了mask遮罩`-webkit-mask-image: url()`;
[【图标】iconfont.css](https://github.com/cumany/Blue-topaz-examples/blob/main/.obsidian/snippets/%E3%80%90%E5%9B%BE%E6%A0%87%E3%80%91iconfont.css)
使用了`background-image: url`来添加背景图案

**Comment by guopenghui** [comment]
![image](https://user-images.githubusercontent.com/13451866/209060666-0f3f11b4-d97c-465f-be72-f58552521007.png)

**Comment by sche11** [comment]
> ![image](https://user-images.githubusercontent.com/13451866/209060666-0f3f11b4-d97c-465f-be72-f58552521007.png)

期待

**Comment by guopenghui** [comment]
词典图标在 `0.2.5` 实现
