### ISSUE TITLE
添加^^^article 和^^^words标记不起作用

### ISSUE THREAD

**Issue by jenningsloy318** [guopenghui/obsidian-language-learner#8]
你好，

我新建一个文档，从the economist里面复制的内容，添加添加^^^article 和^^^words标记不起作用，请问这可能是哪里的问题
![image](https://user-images.githubusercontent.com/10169236/173104682-77d43cee-3eac-49ad-94c4-31f5d0ac4ff3.png)

**Comment by guopenghui** [comment]
应该点右上角那个更多按钮，然后在里面打开阅读模式。
不是切换到markdown的预览模式

**Comment by jenningsloy318** [comment]
@guopenghui 
还有个问题，新单词加入submit了后，我要复习单词怎么弄呢？ 我安装了spaced repetition，复习卡片是空的
![image](https://user-images.githubusercontent.com/10169236/173369127-69047d43-321a-4644-84a3-934a9e4389be.png)


我在添加单词的时候加了tag 
![image](https://user-images.githubusercontent.com/10169236/173369252-beaf717c-d41a-4dcf-8e76-0db645db6a86.png)
这个要怎么操作？

**Comment by jenningsloy318** [comment]
@guopenghui  还有个问题，我添加单词的时候，加了多个tag，但是最后review的文件里面都是只有一个tag，就是`#word`
![image](https://user-images.githubusercontent.com/10169236/173379556-bfddb99d-d47a-4d99-8a41-c636c6b447e6.png)
这个又是怎么回事呢

**Comment by guopenghui** [comment]
现在tag没有实际用到。

你在review的笔记开头加一个#flashcards，就能找到复习的单词了。
#flashcards和#word只是为了标识复习单词，让spaced repetition插件能辨认出来。  和添加单词时的tag无关（现在还没有地方用到这个字段）

**Comment by jenningsloy318** [comment]
好的，明白了，谢谢
