### ISSUE TITLE
使用两台电脑时, 高亮单词数据库好像无法自动同步

### ISSUE THREAD

**Issue by zhuwenfa999** [guopenghui/obsidian-language-learner#81]
同步所有的文件夹(含.obsidian文件夹)后, 也无法自动同步IndexedDB里面的那个数据库...能有解决办法吗?

**Comment by guopenghui** [comment]
目前只能通过设置里面导入导出来在不同电脑间转移数据。无法通过库同步。

indexedDB不在库中，而是在obsidian软件的数据文件夹中。

**Comment by hustrjh** [comment]
@guopenghui 请问是否可能自定义indexDB数据库的路径？比如把数据库放在Ob库中或插件文件夹内，可在同步库文件时同步数据库数据。同步数据库的功能真的挺需要的~ :pray:
