### ISSUE TITLE
请问如何删除库中的某个单词？

### ISSUE THREAD

**Issue by wuzhen97** [guopenghui/obsidian-language-learner#88]

**Comment by gaoyanmin0818** [comment]
看视频教程在数据库中找到单词delete

**Comment by wuzhen97** [comment]
那有点不太聪明的丫子😂，我以为能在那个单词列表删除呢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月17日(周二) 晚上7:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [guopenghui/obsidian-language-learner] 请问如何删除库中的某个单词？ (Issue #88)




 
看视频教程在数据库中找到单词delete
