### ISSUE TITLE
重装Obsidian软件后，数据会丢失吗？

### ISSUE THREAD

**Issue by maxhytv** [guopenghui/obsidian-language-learner#9]
不太懂数据库方面，主要经常会更换电脑，担心会丢失单词数据

**Comment by guopenghui** [comment]
重装不会。 数据库是存在indexedDB中，和Obsidian的软件本体是分开的。比如在我电脑上：

ob在`C:\Users\penghui\AppData\Local\Obsidian`，ob的indexedDB在`C:\Users\penghui\AppData\Roaming\obsidian\IndexedDB`

但是这个数据库是仅在本地保存的，不太清楚你说的换电脑是指什么？如果在另一台电脑上新装了ob，肯定是没有数据的。

**Comment by maxhytv** [comment]
> 重装不会。 数据库是存在indexedDB中，和Obsidian的软件本体是分开的。比如在我电脑上：
> 
> ob在`C:\Users\penghui\AppData\Local\Obsidian`，ob的indexedDB在`C:\Users\penghui\AppData\Roaming\obsidian\IndexedDB` ob在重装的时候只会清除软件本体，不会清除indexedDB
> 
> 但是这个数据库是仅在本地保存的，不太清楚你说的换电脑是指什么？如果在另一台电脑上新装了ob，肯定是没有数据的。
-----------------
感谢回复，今天看到了有导出和导入数据库的功能，实在太棒了；因为我经常需要更换机位，所以在意数据库
-----------------
我还有第二个问题，想请教是否添加批量导入生词的功能？

**Comment by guopenghui** [comment]
> 我还有第二个问题，想请教是否添加批量导入生词的功能？

生词是指哪些词呢？如果是不关心的词，现在是有这个功能的，在阅读视图里面点一下完成阅读，就会把当前页面里面的蓝底词都按照`无视`添加进去。

**Comment by maxhytv** [comment]
> > 我还有第二个问题，想请教是否添加批量导入生词的功能？
> 
> 生词是指哪些词呢？如果是不关心的词，现在是有这个功能的，在阅读视图里面点一下完成阅读，就会把当前页面里面的蓝底词都按照`无视`添加进去。

以前kindle阅读以及平时纸质英文文档中，积累很多生词；以前是导入anki中复习，前天发现您这个插件，用起来很爽，我想是否可以将我以前积累的生词一键导入到ob库？

**Comment by guopenghui** [comment]
有没有标准的格式呢？如果兼容而且使用比较普遍的话后面可以考虑做一个这样的功能。

**Comment by maxhytv** [comment]
能不能参考anki那种，直接txt文档，内容用tab隔开，第一列单词，第二列单词解释，第三列例句等等

**Comment by maxhytv** [comment]
还有大佬，单词复习时候是没有语音的， 我现在是使用quicker添加读音，效果很不错，我想直接使用插件应该也很容易完成
-------
因为ob是支持html的，所以我是直接在里面调用有道的语音，只需要将下面的汉字“单词”修改为英文，可以直接在ob输出语音，希望对大佬有所帮助
-------
<audio  
src="http://dict.youdao.com/dictvoice?audio=单词" controls="controls"> 
</audio>

**Comment by guopenghui** [comment]
> ## 还有大佬，单词复习时候是没有语音的， 我现在是使用quicker添加读音，效果很不错，我想直接使用插件应该也很容易完成
> ## 因为ob是支持html的，所以我是直接在里面调用有道的语音，只需要将下面的汉字“单词”修改为英文，可以直接在ob输出语音，希望对大佬有所帮助
> ```
> <audio  
> src="http://dict.youdao.com/dictvoice?audio=单词" controls="controls"> 
> </audio> 
> ```

👍 我最近也在考虑怎么给复习加语音，这个很有帮助
